[package]
name = "echidna-shim"
version = "0.1.0"
edition = "2021"

[dependencies]
echidna-util = { path = "../echidna-util" }
cacao = "0.3.2"
home = "0.5.9"
log = "0.4.21"
simple-logging = "2.0.2"
url = "2.5.1"
