[package]
name = "echidna-lib"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
echidna-helpers = { path = "../echidna-helpers" }
echidna-shim = { path = "../echidna-shim" }
handlebars = "5.1.2"
serde_json = "1.0.117"
tempdir = "0.3.7"
